### ISSUE TITLE
Plugin does not work on Moodle 3.5

### ISSUE THREAD

**Issue by ing-arriola** [moodleuulm/moodle-local_profiletheme#10]
I installed the plugin in Moodle 3.5 but it does not change the themes when a user logs in.
My form of installation has followed the steps published in the following link:
https://github.com/moodleuulm/moodle-local_profiletheme/blob/master/README.md
But there is only something that I do not understand and what I have done according to what I have found on the net and it has to do with the personalized field; in the case what I could not do is:

"If no custom user profile fields have been defined in your Moodle installation, you need to define custom user profile fields first on /user/profile/index.php before you can add rules here."

This I do it in the following way:
Administrators can create new user profile categories and fields in Administration> Site administration> Users> Accounts> User profile fields.

And the plugin recognizes me the fields but it does not work because if I enter with a user A of custom field of value "A" it gives me the same theme as user B of custom field of value "B". That is to say that A and B even though they have different values ​​continue to receive the same Theme.

I hope you can help me with this since I searched the net and I find absolutely nothing.

![image](https://user-images.githubusercontent.com/37816437/45977104-d2df0200-c005-11e8-9a0f-3ef4e61e1353.png)

Thanks & Regards

**Comment by abias** [comment]
Hi @ing-arriola ,

thank you for your request and especially your screenshot.

Looking at the screenshot, I can tell that each user who logs in and has exactly the value "Mecanico" in his "EnterpriseFunktion" profile field should get the Clean theme delivered.
Everyone else will get the theme delivered which is set on /theme/index.php as the Moodle instance's theme. If this is also Clean, absolutely every user will get the Clean theme.

Please make sure that
1. the "EnterpriseFunction" custom profile field of the users contain any meaningful values. If you just created the custom profile field but did not fill any values into it for each user, the plugin will not work
2. the theme which will be delivered by the plugin is different from the default theme configured in Moodle
3. you log in freshly with the user who should get a theme delivered by the plugin. The ruleset is only processed at login time.
4. there are no course or category themes override the theme set by this plugin. This is described in the last paragraph of https://github.com/moodleuulm/moodle-local_profiletheme#how-this-plugin-works--pitfalls

**Comment by ing-arriola** [comment]
Hi @abias 

I have tried to enter not with one but with several users that have the "Mecanico" value in their enterpriseFunction field and I have also defined other users with a different value in that field, but the topic remains unchanged. My original intention is that users with "Mecanico" value receive the theme Fordson and users with value "Admin" receive the theme "Clean", finally the users or with the value "School" receive the theme Enligthlite.

![image](https://user-images.githubusercontent.com/37816437/46094738-ef9b4700-c177-11e8-8d43-827d87c5f8e3.png)

**Comment by abias** [comment]
Hi @ing-arriola ,

I am sorry that I was not able to come back to this issue anymore last year.

Can you please give me a quickupdate if you were able to figure out a solution on your side or if this problem persists for you?

Cheers,
ALex

**Comment by abias** [comment]
Hi @ing-arriola ,

I am closing this issue now. If you encounter any more problems, don't hesitate to come back to me.

Cheers,
Alex
