### ISSUE TITLE
Feature proposal

### ISSUE THREAD

**Issue by FrankyJust** [moodleuulm/moodle-local_profiletheme#11]
Hello,

I've tested this plugin (M3.6.2) and it works very fine. I was thinking if in future development, it would be possible to add validation on the input field in case the field is added as required textfield to a signup form. A user now can fill in anything, and when the input doesn't match one of the predefined items, then the default theme is added (which an admin probably will prevent). It would be nice if there would be a check if the input matches one of the predefined items, and if not, no account can be registered. A new user can so only register when he fills in the correct item, which item is communicated in advance to the user.

Franky

**Comment by abias** [comment]
Hi Franky,

thank you for your idea.

However, I think you are putting the cart before the horse. The one and only purpose of this plugin is to map custom profile field values to the delivered theme. It does neither care how and by what mechanism the custom profile fields are filled nor does it care if the configured custom profile field values are really set for any user.

If you really want to have a check in the signup form if a value of a custom field is configured in local_profiletheme, you will most probably have to develop a custom profile field type for your own needs which includes this check.

Cheers,
Alex
