### ISSUE TITLE
different themes are not displayed

### ISSUE THREAD

**Issue by andreajuettner** [moodleuulm/moodle-local_profiletheme#16]
Hello!
I installed the plugin, then created a profile field (as a dropdown) and added new rules Institution 1,2,3 and mapped them to the custom user profile fields. So far so good, everything fine. Then I customized each user's profile field to "Institution 1,2,3 etc". The following happened:

a) for existing users > the theme for "Institution 1" is not displayed
b) for a new user > the theme for "Institution 1" is displayed
c) in the new user (b) profile field "Institution 1" changed to another "Institution 2" > theme for "Institution 2" is not displayed
and so on.

Have I overlooked any settings? Is the profile field not working as a dropdown selection? Or is this a bug? I have installed Moodle 4.3.
I look forward to your feedback.
Thank you!

**Comment by abias** [comment]
Hi @AnnieHy ,

I am really sorry that this issue has not been handled yet.
From my point of view, dropdown fields should be fully supported. Basically, you confirm this yourself as your mappings seem to work for new users.

The only thing I can think of currently is the possibililty that you might have overseen that the rules are only evaluatated at login time. You cannot change the theme of a user for an existing session.

Cheers,
Alex
