### ISSUE TITLE
String nofields must not define the URL like this

### ISSUE THREAD

**Issue by mudrd8mz** [moodleuulm/moodle-local_profiletheme#6]
Currently the string `$string['nofields']` has a text like `<br>You need to <a href="/user/profile/index.php">define custom user profile fields</a>`. Such a link does not work on sites that have moodle installed in a subdirectory.

Generally, it is better not to hard-code URLs in the strings. Replace the actual URL with a `{$a}` placeholder and generate the correct moodle_url instance in the PHP code.

**Comment by abias** [comment]
Thanks, David, for pointing this out. Once again, I missed this possibility of running Moodle in a subdir.

Fixed in 594b692bd7bd5577b218323bc288e516e57c6377.
