### ISSUE TITLE
Login As does not show the right theme

### ISSUE THREAD

**Issue by jrojas-garrido** [moodleuulm/moodle-local_profiletheme#8]
When I go to a user profile and then click on `login in as` link.  The interface does not take consideration of the configuration and show the default theme of the user, not the theme of the configuration of this plugin.

example ` http://localhost:80/moodle/course/loginas.php?id=1&user=3&sesskey=QnBQ2hRJP8

**Comment by abias** [comment]
Hi Jose,

Thank you for raising this issue and the pull request. This is a reasonable request.

We will verify and include the patch within our upcoming Moodle 3.4 release.

Thanks,
Alex

**Comment by nicoroeser** [comment]
Fix merged in commit 961d17bc28f9c23f83f2af4806f22b4e3a72b784. Thanks!
